""" This file is automatically generated from "mitsuba.conf" using the script
    "resources/configure.py". Please do not attempt to change it manually,
    as any changes will be overwritten."""

PYTHON_EXECUTABLE = r"/home/huan/miniconda3/bin/python"
MTS_DEFAULT_VARIANT = ''
MTS_VARIANTS = ['scalar_rgb', 'scalar_spectral']
